<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>Office-stamper</name>
    <groupId>pro.verron</groupId>
    <artifactId>office-stamper</artifactId>
    <version>3.8-SNAPSHOT</version>
    <description>
        Office-stamper is a Java library for stamping DOCX templates with data.
        It allows you to create professional documents by merging data with
        pre-designed templates, supporting various features like tables, images,
        and conditional content.
    </description>
    <packaging>pom</packaging>
    <url>https://office-stamper.verron.pro</url>
    <inceptionYear>2022</inceptionYear>

    <modules>
        <module>engine</module>
        <module>excel-context</module>
        <module>cli</module>
        <module>utils</module>
    </modules>

    <properties>
        <docx4j.version>11.5.14</docx4j.version>
        <asciidoc.version>3.9</asciidoc.version>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.report.outputEncoding>UTF-8</project.report.outputEncoding>

        <maven.compiler.release>25</maven.compiler.release>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.simplify4u.plugins</groupId>
                <artifactId>sitemapxml-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>3.11.0</version>
                    <executions>
                        <execution>
                            <id>unpack-css</id>
                            <phase>generate-resources</phase>
                            <goals>
                                <goal>unpack</goal>
                            </goals>
                            <configuration>
                                <artifactItems>
                                    <artifactItem>
                                        <groupId>pro.verron</groupId>
                                        <artifactId>maven-skin</artifactId>
                                        <version>1.0.12</version>
                                        <outputDirectory>${project.build.directory}/unpacked-css</outputDirectory>
                                        <includes>**/*.css</includes>
                                    </artifactItem>
                                </artifactItems>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>3.9.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-report-plugin</artifactId>
                    <version>3.5.6</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.15.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>3.8.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.12.0</version>
                    <configuration>
                        <stylesheetfile>${project.build.directory}/unpacked-css/css/javadoc.css</stylesheetfile>
                    </configuration>
                    <executions>
                        <execution>
                            <id>attach-javadocs</id>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.4.0</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.6</version>
                    <configuration>
                        <redirectTestOutputToFile>true</redirectTestOutputToFile>
                        <systemPropertyVariables>
                            <java.awt.headless>true</java.awt.headless>
                        </systemPropertyVariables>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.22.0</version>
                    <configuration>
                        <generateSitemap>true</generateSitemap>
                        <generateProjectInfo>true</generateProjectInfo>
                        <generateReports>true</generateReports>
                        <attributes>
                            <source-highlighter>coderay</source-highlighter>
                            <coderay-css>style</coderay-css>
                        </attributes>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.apache.maven.reporting</groupId>
                            <artifactId>maven-reporting-exec</artifactId>
                            <version>2.0.1</version>
                        </dependency>
                        <dependency>
                            <groupId>org.asciidoctor</groupId>
                            <artifactId>asciidoctor-parser-doxia-module</artifactId>
                            <version>3.2.0</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.8.15</version>
                    <executions>
                        <execution>
                            <id>prepare-agent</id>
                            <goals>
                                <goal>prepare-agent</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>report</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>report</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.sonatype.central</groupId>
                    <artifactId>central-publishing-maven-plugin</artifactId>
                    <version>0.11.0</version>
                    <extensions>true</extensions>
                    <configuration>
                        <publishingServerId>central</publishingServerId>
                        <autoPublish>true</autoPublish>
                        <waitUntil>published</waitUntil>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.pitest</groupId>
                    <artifactId>pitest-maven</artifactId>
                    <version>1.25.5</version>
                </plugin>
                <plugin>
                    <groupId>org.simplify4u.plugins</groupId>
                    <artifactId>sitemapxml-maven-plugin</artifactId>
                    <version>2.2.0</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>gen</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>pro.verron.office-stamper</groupId>
                <artifactId>engine</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.office-stamper</groupId>
                <artifactId>utils</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.office-stamper</groupId>
                <artifactId>cli</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.excel</groupId>
                <artifactId>excel-context</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.asciidoc</groupId>
                <artifactId>asciidoc-core</artifactId>
                <version>${asciidoc.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.asciidoc</groupId>
                <artifactId>asciidoc-converters</artifactId>
                <version>${asciidoc.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.asciidoc</groupId>
                <artifactId>asciidoc-docx</artifactId>
                <version>${asciidoc.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.asciidoc</groupId>
                <artifactId>asciidoc-compiler</artifactId>
                <version>${asciidoc.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.asciidoc</groupId>
                <artifactId>asciidoc-preview</artifactId>
                <version>${asciidoc.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.imageio</groupId>
                <artifactId>imageio-svg</artifactId>
                <version>3.4</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.imageio</groupId>
                <artifactId>imageio-wmf</artifactId>
                <version>3.4</version>
            </dependency>
            <dependency>
                <groupId>pro.verron.imageio</groupId>
                <artifactId>imageio-emf</artifactId>
                <version>3.4</version>
            </dependency>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>6.1.3</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.docx4j</groupId>
                <artifactId>docx4j-JAXB-ReferenceImpl</artifactId>
                <version>${docx4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.xmlgraphics</groupId>
                <artifactId>batik-transcoder</artifactId>
                <version>1.19</version>
                <exclusions>
                    <exclusion>
                        <groupId>xml-apis</groupId>
                        <artifactId>xml-apis</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.xmlgraphics</groupId>
                <artifactId>batik-codec</artifactId>
                <version>1.19</version>
                <exclusions>
                    <exclusion>
                        <groupId>xml-apis</groupId>
                        <artifactId>xml-apis</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>info.picocli</groupId>
                <artifactId>picocli</artifactId>
                <version>4.7.7</version>
            </dependency>

            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-context</artifactId>
                <version>7.0.8</version>
            </dependency>

            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-jdk14</artifactId>
                <version>2.0.18</version>
            </dependency>
            <dependency>
                <groupId>com.opencsv</groupId>
                <artifactId>opencsv</artifactId>
                <version>5.12.0</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.22.0</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.22.0</version>
            </dependency>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm</artifactId>
                <version>9.10.1</version>
            </dependency>
            <dependency>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>1.25.5</version>
            </dependency>
            <dependency>
                <groupId>org.jspecify</groupId>
                <artifactId>jspecify</artifactId>
                <version>1.0.0</version>
                <scope>compile</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-report-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>javadoc</report>
                            <report>test-javadoc</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <reportSets>
                    <reportSet>
                        <reports>
                            <!-- select non-aggregate reports -->
                            <report>report</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>

    <profiles>
        <profile>
            <id>gpg</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>3.2.8</version>
                        <configuration>
                            <bestPractices>true</bestPractices>
                        </configuration>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <distributionManagement>
        <site>
            <id>GitHub Page</id>
            <name>Office-stamper Documentation</name>
            <url>https://office-stamper.verron.pro</url>
        </site>
    </distributionManagement>

    <organization>
        <name>Verron.pro</name>
        <url>https://verron.pro</url>
    </organization>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>LICENSE</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <email>joseph@verron.pro</email>
            <name>Joseph Verron</name>
            <url>https://verron.pro</url>
            <organization>Verron.pro</organization>
            <organizationUrl>https://verron.pro</organizationUrl>
            <roles>
                <role>Lead Developer</role>
            </roles>
            <timezone>Beijing</timezone>
        </developer>
    </developers>

    <scm>
        <url>https://github.com/verronpro/office-stamper</url>
        <developerConnection>scm:git:https://github.com/verronpro/office-stamper.git</developerConnection>
        <connection>scm:git:https://github.com/verronpro/office-stamper.git</connection>
    </scm>
</project>
